INSERT INTO custom_providers (
  id,
  organization_id,
  name,
  label,
  url,
  token,
  api_key,
  api_key_source,
  format,
  headers,
  prefix)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11)
RETURNING
  id AS "id: CustomProviderId",
  organization_id AS "organization_id: crate::models::organization::OrganizationId",
  updated_at,
  created_at,
  name,
  label,
  url,
  token,
  api_key,
  api_key_source,
  format AS "format: ProviderRequestFormat",
  headers,
  prefix,
  'owner' AS "_permission!: filigree::auth::ObjectPermission"
