name = "Alias"
plural = "Aliases"
standard_endpoints = true

[[fields]]
name  = "name"
type = "text"
nullable = false
description = "The name of the alias, to reference it in API calls"

[[fields]]
name = "random_order"
type = "boolean"
default = false
nullable = false
description = "If there are multiple providers, start with a random provider instead of the first one"

[[has]]
model = "AliasModel"
many = true
field_name = "models"
populate_on_get = 'data'
