[package]
name = "chronicle-proxy"
version = "0.1.0"
edition = "2021"
description = "LLM Abstraction"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.80"
backon = "0.4.4"
bytes = "1.6.0"
error-stack = "0.4.1"
filigree = { workspace = true, optional = true }
reqwest = "0.12.3"
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"
sqlx = { version = "0.7.4", features = ["any"] }
thiserror = "1.0.58"
tokio = { version = "1.37.0", features = ["time"] }
tracing = "0.1.40"

[features]
default = ["postgres"]
any-db = ["sqlx/any"]
postgres = ["sqlx/postgres"]
sqlite = ["sqlx/sqlite"]
filigree = ["dep:filigree"]
